node('Jenkins_Slave'){
    
    stage('Code Checkout'){
        git 'https://github.com/bhanudevops2019/test_studentapp-ui.git'
    }

    stage("Compile"){
          sh '''
          mvn compile
          '''
    }

    stage('Code Quality Check'){
        sh '''
mvn sonar:sonar \
  -Dsonar.projectKey=bhanudevops2019_test_studentapp-ui \
  -Dsonar.organization=bhanudevops2019-github \
  -Dsonar.host.url=https://sonarcloud.io \
  -Dsonar.login=a2bf29f527084fbbb7e5ac525851c8069592ba0e        
        '''
    }
}